version: '3'
services:
  postgresql:
    image: postgres:14.3-alpine3.16
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
