version: '3'
services:
  postgresql:
    image: postgres:14.3-alpine3.16
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data